### ISSUE TITLE
Reorganize Nav bar

### ISSUE THREAD

**Issue by gp3man** [gp3man/TonyThymeBlog_next_v1#5]
- [x] tony thyme logo centered
- [x] scratch out recipes link
- [ ] add "I truly believe that no one deserves to eat boring food, and i aim to put a stop to it, plate by plate!" above recipes and below logo

**Comment by gp3man** [comment]
- [x] need feedback on the current navbar @brny09

**Comment by brny09** [comment]
I think ideally, I would like it if I typed in the word "fish" tuna and salmon recipes would show up. Is there a way to add tags like, seafood, pescatarian, fish, etc?
